### ISSUE TITLE
How to get insert ID?

### ISSUE THREAD

**Issue by shtse8** [dustingraham/react-mysql#2]
I want to get the id of the last insert. How can I?

**Comment by dustingraham** [comment]
I don't have a project set up with this right now.

Have you tried

```
$db->statement('INSERT INTO ...', [...data...])
    ->then(function(\mysqli_result $result)
    {
        $id = $result->insert_id;
    });
```

**Comment by shtse8** [comment]
http://php.net/manual/en/class.mysqli-result.php

I can't see there is a `insert_id` property in mysqli_result.

It's in the stmt class.
http://php.net/manual/en/class.mysqli-stmt.php

**Comment by dustingraham** [comment]
I see what you mean. I was looking in the wrong place.

I found: http://php.net/manual/en/mysqli.insert-id.php

But, this likely isn't going to work with the async nature of the code.

I'm sorry, I don't know how to get the id of the last insert.

**Comment by shtse8** [comment]
Can the class return the `mysqli` object so we can get the id of the last insert?

**Comment by shtse8** [comment]
Do you think it's a workaround to this?
https://github.com/M2Mobi/lunr/blob/master/src/Lunr/Gravity/Database/MySQL/MySQLAsyncQueryResult.php

```
protected function fetch_result()
    {
        if ($this->fetched === TRUE)
        {
            return;
        }
        $this->result = $this->mysqli->reap_async_query();
        if (is_object($this->result))
        {
            $this->success = TRUE;
            $this->freed   = FALSE;
        }
        else
        {
            $this->success = $this->result;
            $this->freed   = TRUE;
        }
        $this->fetched = TRUE;
        $this->error_message = $this->mysqli->error;
        $this->error_number  = $this->mysqli->errno;
        $this->insert_id     = $this->mysqli->insert_id;
        $this->affected_rows = $this->mysqli->affected_rows;
        $this->num_rows      = is_object($this->result) ? $this->result->num_rows : $this->affected_rows;
    }
```

```
    public function insert_id()
    {
        $this->fetch_result();
        return parent::insert_id();
    }
```

**Comment by shtse8** [comment]
https://github.com/KhristenkoYura/react-mysql/blob/master/src/Client.php

I can see some people just get the insert id from the connection when the result is back.
But I am not sure what it will happen if multiple inserts are running and returning at the same time.

**Comment by dustingraham** [comment]
Ah, I see what you mean.

So then here : https://github.com/dustingraham/react-mysql/blob/master/src/Database.php#L106

Where the line `$deferred->resolve($result);` is, you would need to pass in `$read` to the promise resolve callback. I have not worked on this code in over a year, so I don't have the setup currently to test and implement this. I'm not sure whether the resolve call would need an array, or if it can add another parameter.

You might just need to add the parameter so `$deferred->resolve($result, $read);` and then add the mysqli object to ` ->then(function(\mysqli_result $result, $mysqli)` but I can't say for sure. That does look promising based on the link you provided.

**Comment by dustingraham** [comment]
Ah, yes, what you just pointed out seems good as well.

I think it would work because you're calling the insert id before releasing the mysqli that is being reaped.

**Comment by shtse8** [comment]
Thanks. Let me try.
